---
title: "Content"
---

<iframe src="https://giphy.com/embed/ftAyb0CG1FNAIZt4SO" width="480" height="270" align= "right" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>

This course introduces **data science** technologies and techniques to study communication processes and effects in novel and innovative ways. Learning data science and computational methods is useful because it provides new skills and much thought-after qualifications in the job market, but also allows us to tap into new areas of research and to gain a better understanding of today’s society. 

On the one hand, this both enables and incentivizes us to expand our **methodological toolkit**. To study political communication, we can now turn our gaze to countless communication artifacts from political parties and organizations. In media psychological research, we can make use of log data and advanced analytical procedures to measure effects at new and fine-grained levels. In the field of corporate communication, the rise of social media as central communication platforms not only requires our attention, but also enables new ways to study marketing and public relations in a natural setting and on a massive scale.

On the other hand, the digital era has also given way to new **key phenomena in communication** that are difficult to understand without a general understanding of data science technologies. Indeed, scientists are not the only ones using these technologies. More and more facets of digital life are becoming at least partially managed by algorithms. Decisions of journalists, politicians, and organizations are increasingly based on metrics of collective human behavior. In the best cases, these developments can enhance lives. In the worst cases, they can foster fake news and undermine democracy. In all cases, it is becoming increasingly difficult to understand the impact of these developments without knowing the possibilities and limits of computers.

In the course, students will learn about common **computational methods in Communication Science**. They will learn how to use the statistical programming environment R to a) import various data formats as well as gather data from online sources, b) transform and wrangle data to get it ready for analysis, c) perform text analysis (including machine learning approaches), d) perform advanced statistical methods in independent research projects (e.g., time series analysis, multilevel analysis, factor analyses and structural equation modeling, analysis of variance based on experimental data).

Based on a problem-based learning approach, each lecture introduces a new empirical problem and discusses methods and statistical approaches that can solve the problem. Students then learn how to conduct these methodological solutions in the practical sessions and are given the opportunity to further practice these approaches in further homework assignments. 

<br>

## Learning goals

After completion of the course, students will...

- know the most important (computational) methods to analyze digital communication
- be able to identify data analytical problems and challenges, analyze them critically, and find appropriate solutions 
- be able to read, understand, and criticize recent communication research

With regard to the specific methods being taught, students will be able to... 

- gather, scrape, and import data from different file types, APIs, and websites
- link data from different sources to create new insights
- clean and transform messy data into a tidy data format ready for analysis
- conduct computational text analysis and use machine learning techniques to extract useful information from textual data
- perform advanced statistical analyses (e.g., time series analysis, structural equation modeling, linkage analysis…)
