---
title: "Materials"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    df_print: paged
---

On this page, you'll find all materials (e.g., slides, handouts, R-syntax, etc.) for this course.

<br>

## Preparation

#### Install R and RStudio

Before the first practical session, please make sure that you have R and Rstudio installed on your computer and have played around a little with it (it is open source and free to use). Please work through the initial steps outlined in these two worksheets:

- [Installing R and RStudio](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/R_basics_1_getting_started_short.md). 
- [R Basics](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_basics_introduction.md)

#### Familiarize yourself with the course

Lectures are every *Monday* from 13.30-15.15 (see [overview](overview.html) for exact dates and times). In these lectures, a particular research problem will be introduced and we will discuss methodological solutions. We will get to know respective computational methods and contextualize them within the broader research process. Practical sessions are every **Tuesday* and *Thursday* between 9-10.45 or 11-12.45 (again see [overview](overview.html) for exact dates and times). For the practical sessions, the class will be split into 6 groups of equal size. In these practical sessions, we will work with RStudio and ran analyses on real-world data sets. We therefore engage in various data analytic exercises. We expect you to: 

- Bring your own computer
- Run the scripts and work through the code 
- Ask questions and participate!

In the third part of the course, students will work on their own research projects. Resources and material for additional methods and statistical approaches will be provided to all students. 


<br>
<hr>

## Week 1

#### Lecture: Introduction to Computational Methods in Communication Science

- Slides Lecture 1:
    - [Download Slides](slides/01_introduction_2023.html)

#### Practical Session 1: Data Wrangling

- Handouts: 
    - [Intro to the tidyverse](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_tidy_transforming-and-summarizing.md) ([With Solutions](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_tidy_transforming-and-summarizing_complete.md))
    
#### Practical Session 2: Data visualization

- Handouts:
    - [Data visualization](https://github.com/vanatteveldt/ccslearnr/blob/master/handouts/ggplot.md) ([With Solutions](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_basics_ggplot.md))
   
#### Homework

- Work through this tutorial: 
    - [R Markdown: Basics](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_basics_r-markdown.md)
    - [R Markdown: Demonstration Video](https://canvas.vu.nl/courses/71798/files/6906449?module_item_id=1165159)
    - [R Markdown: Additional material](https://rmarkdown.rstudio.com/lesson-1.html)

- Complete this assignment (available on canvas in the modules "Homework Assignments" & "Data Sets)
    - 01_homework_assignment.rmd
 

#### Additional resources


- Chapter 5 & 6 in [Computational Analysis of Communication](https://cssbook.net/) by Van Atteveldt et al. 
- [Online book "R for Data Science"](https://r4ds.had.co.nz/) (Very good resource!)
- [Online book "Data Visualization" by Kieran Healy](https://socviz.co/) (Great book on good visualizations)
- [Website "Data-To-Viz" (great overview on visualizations with code examples)](https://www.data-to-viz.com/) (A website with a lot of examples and R Code)

<br>
<hr>

## Week 2

#### Lecture: Automated Text Analysis and Dictionary Approaches

- Slides Lecture 2:
    - [Download Slides](slides/02_textanalysis_2023.html)

#### Practical Session 1

- Handouts: 
    - [Basic Text Analysis using tidytext](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_basics-of-text-analysis_2023.md) ([With Solutions](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_basics-of-text-analysis_2023_complete.md))
   

#### Practical Session 2 

- Handouts: 

   - [Dictionary Approaches using tidytext](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_dictionary-approaches_2023.md) ([With Solutions](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_dictionary-approaches_2023_complete.md))
   
#### Homework

- Complete this assignment (available on canvas in the module "Homework Templates & Datasets)
    - 02_homework_assignment.rmd 

#### Additional resources

- Chapter 9 & 10 in [Computational Analysis of Communication](https://cssbook.net/) by Van Atteveldt et al. 

<br>
<hr>

## Week 3

#### Lecture: Text Classification and Classic Machine Learning

- Slides Lecture 3:
    - [Download Slides](slides/03_classicmachinelearning_2024.html) 

#### Practical Session 1

- Handouts: 
    - [Supervised text classification using Neural Networks](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_supervised-text-classification-II_2023.md) ([With Solutions](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_supervised-text-classification-II_2024_complete.md))

#### Practical Session 2

- Handouts:
    - [Supervised text classification with word-embeddings and neural networks](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_LLM_word-embeddings_2024.md) ([Link to Online Tutorial](https://youtu.be/joLr1EfGfpI)) ([With Solutions](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_LLM_word-embeddings_2024_complete.md))
    

#### Homework

- Complete this assignment (available on canvas in the module "Homework Templates & Datasets)
    - 03_homework_assignment.rmd 
    
#### Additional resources: 

- Chapter 8 & 11 in [Computational Analysis of Communication](https://cssbook.net/) by Van Atteveldt et al. 
- [Supervised Machine Learning for Text Analysis in R](https://smltar.com/) (Online Book on Machine Learning in R)
- 3Blue1Brown: [What is a neural network?](https://www.youtube.com/watch?v=aircAruvnKk) (Fantastic explanation of basic principles by 3Blue1Brown)

<br>
<hr>

## Week 4

#### Lecture: Transformers and Large Language Models

- Slides Lecture 4:
    - [Download Slides](slides/04_largelanguagemodels_2024.html)

#### Practical Session 1

- Handouts: 
    - [Zero-Shot Text classification using GPT and LLama](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_LLM_zero-shot-classification_2024.md) ([With solutions](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text_LLM_zero-shot-classification_2024_complete.md))

#### Practical Session 2

- Handouts:
    - [Few-Shot Classification using GPT/Llama](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text-LLM_few-shot-classification.md) ([With Solutions](https://github.com/masurp/VU_CADC/blob/main/tutorials/R_text-LLM_few-shot-classification_complete.md))
    

#### Homework

- Complete this assignment (available on canvas in the module "Homework Templates & Datasets)
    - 04_homework_assignment.rmd
    
#### Additional resources: 

- The "original" [transformer paper](https://arxiv.org/abs/1706.03762) by Vaswani et al. 2017.
- A fun, but suprisingly detailed [Intro to GPT](https://youtu.be/wjZofJX0v4M?si=psd17zf5dA0W6EjK) on Youtube (3Blue1Brown)

<br>
<hr>

## Week 5

#### Exam week 

- Date and Time of the Exam
    - **Date:** 29th November 2024
    - **Time:** 08:30am
    - **Location:** t.b.a
    - Make sure to be there on time
    
- Format
    - The exam will be on **TestVision**
    - It consists of Multiple Choice Questions & Open Questions
    - Example questions are provided at the end of all lecture slides

- What do you need to know?
    - Content of the lectures
    - The required readings (see lecture slides and Canvas)
    - The practical sessions will further help to deepen your understanding of the concepts and approaches (e.g., how to interpret results). While you will not be required to write R code in the exam, we expect you to be able to read it and interpret R output.

<br>
<hr>

## Week 6 & 7

#### Introduction to Group Research Projects

- Slides Lecture 5:
    - [Download Slides](slides/05_groupprojects.html)
    
#### Additional methods and resources (handouts and video tutorials)

- A general collection of diverse R tutorials
    - [CCS Amsterdam R course material](https://github.com/ccs-amsterdam/r-course-material) 
    
- Basic Statistics in R
    - [Basic Statistics (ANOVA, regression, t-test, etc.)](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/simple_modeling.md) ([Video tutorial](https://www.youtube.com/watch?v=1K3SKsEj9eI)) 
    - [Mediation Analysis](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/mediation_analysis.md)

- Test theory and factor analyses
    - [Test theory and confirmatory factor analyses](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/R_test-theory_1_cfa.md) ([Video tutorial](https://www.youtube.com/watch?v=uKlagNgC-GY))
    - [Exploratory factor analysis](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/R_test-theory_2_efa.md) ([Video tutorial](https://youtu.be/AXaBMDA34YM))
    
- Advanced Statistics
    - [Advanced Statistics Overview](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/advanced_modeling.md)
    - [Generalized linear model](https://htmlpreview.github.io/?https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/generalized_linear_models.html) ([Video tutorial](https://www.youtube.com/watch?v=WnmwuD8OwMw&list=PL-i7GM-A1wBarcTV3wN2f-AAuEK3j76M0&index=3))
    - [Multilevel Modeling](https://htmlpreview.github.io/?https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/multilevel_models.html) ([Video tutorial](https://www.youtube.com/watch?v=1Tw1eIfSyEQ&list=PL-i7GM-A1wBarcTV3wN2f-AAuEK3j76M0&index=4))
    - [Structural Equation Modeling](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/R_sem_1_lavaan.md)
    
- Additional text analysis
    - [LDA topic modeling](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/tidytext-topicmodel.md)
    - [Structural topic modeling](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/r_text_stm.md) ([Video tutorial](https://www.youtube.com/watch?v=37yvQdQw5j8&list=PLjXODJ_lGN_U02yQyZG5YpBgseVpiS9s2&index=3))
    
- Web Scraping
    - [Web scraping using Rvest](https://github.com/ccs-amsterdam/r-course-material/blob/master/tutorials/rvest.md) ([Video tutorial](https://www.youtube.com/watch?v=9GR26Y4z_v4))
    

<br>
<hr>



## Week 8

#### Final presentation at the "mini-conference"

- At a final "mini-conference", you will present the findings of your research projects!

- Date: 16th December 2023

- Time: 13.30 to 17.15

    - More information soon (including exact schedule)

<hr>

<p style = "margin-left: auto; margin-right: 0;">
This course is published under the following [license](https://github.com/masurp/VU_CADC/blob/main/LICENSE.md). 
</p>