```{r setup, include=FALSE, cache = F}
options(htmltools.dir.version = FALSE, width = 36, scipen = 2)
library(knitr)
library(tidyverse)
library(hrbrthemes)
opts_chunk$set(
  comment = "", message = F, warning = F, cache = T,
  fig.width = 6, fig.height = 5, fig.retina = 2, out.width = "100%"
)
```

```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
mono_accent(
  base_color = "#0089cf",
  text_color = "#3c3c3c",
  link_color = "#0089cf",
  text_font_size = "25px",
  background_color = "#ffffff",
  header_color = "#0089cf",
  header_h1_font_size = "53px",
  header_h2_font_size = "40px",
  header_h3_font_size = "33px",
  text_font_google = google_font("Open Sans Condensed", c(300, 700)),
  text_font_weight = "300",
  #header_font_google = google_font("Amatic SC", 700),
  #header_font_weight = "700",
  header_font_google = google_font("Open Sans Condensed", 300) ,
  header_font_weight = "300",
  code_font_google = google_font("Roboto Mono", 300),
  code_font_size = "16px",
  title_slide_text_color = "#3c3c3c",
  title_slide_background_color = "#ffffff",
  text_slide_number_font_size = "1em",
  text_slide_number_color = "#0089cf",
  padding = "0em 2em .5em 2em",
  extra_css = list( ".small code" = list("font-size"="16px"), ".remark-slide thead" = list("background"="none"),
                    ".hljs-github .hljs"  = list("background-color"="#e8e8e8", "padding"="2"),
                    ".pull-left code" = list("border-right"="1px dashed #ccc", "height" = "450px"),
                    ".remark-slide tr:nth-child(even)" = list("background-color"="#f8f8f8"),
                    ".title-slide" = list("background"= "url(https://wwwen.uni.lu/var/storage/images/media/images/lcl_images/vrije_universiteit_amsterdam/1384644-1-fre-FR/vrije_universiteit_amsterdam.png) right bottom no-repeat #fff", "background-size" = "350px; 100px"))
)
```
